name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add NonadiabaticRegistry
        run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="git@github.com:maurergroup/NonadiabaticRegistry.git"))'

      - name: Set Pkg protocol to "ssh" for github
        # run: julia -e 'using Pkg; Pkg.setprotocol!(domain="github.com", protocol="ssh")'
        run: git config --global url."git@".insteadOf "https://"

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1